# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _MosaifyPy_Linux
else:
    import _MosaifyPy_Linux

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class ImageFileLoader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def load(filename):
        return _MosaifyPy_Linux.ImageFileLoader_load(filename)

    @staticmethod
    def write(filename, img):
        return _MosaifyPy_Linux.ImageFileLoader_write(filename, img)

    def __init__(self):
        _MosaifyPy_Linux.ImageFileLoader_swiginit(self, _MosaifyPy_Linux.new_ImageFileLoader())
    __swig_destroy__ = _MosaifyPy_Linux.delete_ImageFileLoader

# Register ImageFileLoader in _MosaifyPy_Linux:
_MosaifyPy_Linux.ImageFileLoader_swigregister(ImageFileLoader)

def ImageFileLoader_load(filename):
    return _MosaifyPy_Linux.ImageFileLoader_load(filename)

def ImageFileLoader_write(filename, img):
    return _MosaifyPy_Linux.ImageFileLoader_write(filename, img)

class RegionOfInterest(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _MosaifyPy_Linux.RegionOfInterest_swiginit(self, _MosaifyPy_Linux.new_RegionOfInterest(*args))
    x = property(_MosaifyPy_Linux.RegionOfInterest_x_get, _MosaifyPy_Linux.RegionOfInterest_x_set)
    y = property(_MosaifyPy_Linux.RegionOfInterest_y_get, _MosaifyPy_Linux.RegionOfInterest_y_set)
    width = property(_MosaifyPy_Linux.RegionOfInterest_width_get, _MosaifyPy_Linux.RegionOfInterest_width_set)
    height = property(_MosaifyPy_Linux.RegionOfInterest_height_get, _MosaifyPy_Linux.RegionOfInterest_height_set)
    __swig_destroy__ = _MosaifyPy_Linux.delete_RegionOfInterest

# Register RegionOfInterest in _MosaifyPy_Linux:
_MosaifyPy_Linux.RegionOfInterest_swigregister(RegionOfInterest)

class Mosaify(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def getMaxThreads(self):
        return _MosaifyPy_Linux.Mosaify_getMaxThreads(self)

    def __init__(self):
        _MosaifyPy_Linux.Mosaify_swiginit(self, _MosaifyPy_Linux.new_Mosaify())
    __swig_destroy__ = _MosaifyPy_Linux.delete_Mosaify

    def getMaxWidth(self):
        return _MosaifyPy_Linux.Mosaify_getMaxWidth(self)

    def getMaxHeight(self):
        return _MosaifyPy_Linux.Mosaify_getMaxHeight(self)

    def setTileSize(self, tileSize):
        return _MosaifyPy_Linux.Mosaify_setTileSize(self, tileSize)

    def getTileSize(self):
        return _MosaifyPy_Linux.Mosaify_getTileSize(self)

    def setPatchSize(self, size):
        return _MosaifyPy_Linux.Mosaify_setPatchSize(self, size)

    def getPatchSize(self):
        return _MosaifyPy_Linux.Mosaify_getPatchSize(self)

    def addTileImage(self, width, height, components, data, filepath, id):
        return _MosaifyPy_Linux.Mosaify_addTileImage(self, width, height, components, data, filepath, id)

    def removeTileImage(self, id):
        return _MosaifyPy_Linux.Mosaify_removeTileImage(self, id)

    def hasTileImage(self, id):
        return _MosaifyPy_Linux.Mosaify_hasTileImage(self, id)

    def getTileImage(self, id, img):
        return _MosaifyPy_Linux.Mosaify_getTileImage(self, id, img)

    def updateTileImage(self, width, height, components, data, filepath, id):
        return _MosaifyPy_Linux.Mosaify_updateTileImage(self, width, height, components, data, filepath, id)

    def updateTileROI(self, x, y, width, height, id):
        return _MosaifyPy_Linux.Mosaify_updateTileROI(self, x, y, width, height, id)

    def getTileROI(self, id):
        return _MosaifyPy_Linux.Mosaify_getTileROI(self, id)

    def generate(self, width, height, components, data):
        return _MosaifyPy_Linux.Mosaify_generate(self, width, height, components, data)

    def getMosaicImage(self, img):
        return _MosaifyPy_Linux.Mosaify_getMosaicImage(self, img)

    def getMosaicJsonArray(self):
        return _MosaifyPy_Linux.Mosaify_getMosaicJsonArray(self)

    def getMosaicMap(self, *args):
        return _MosaifyPy_Linux.Mosaify_getMosaicMap(self, *args)

    @staticmethod
    def scaleNumber(scaleMax, inputMax, inputNumber):
        return _MosaifyPy_Linux.Mosaify_scaleNumber(scaleMax, inputMax, inputNumber)

# Register Mosaify in _MosaifyPy_Linux:
_MosaifyPy_Linux.Mosaify_swigregister(Mosaify)

def Mosaify_scaleNumber(scaleMax, inputMax, inputNumber):
    return _MosaifyPy_Linux.Mosaify_scaleNumber(scaleMax, inputMax, inputNumber)

class Image(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MosaifyPy_Linux.delete_Image

    def __init__(self, *args):
        _MosaifyPy_Linux.Image_swiginit(self, _MosaifyPy_Linux.new_Image(*args))

    def setPixel(self, *args):
        return _MosaifyPy_Linux.Image_setPixel(self, *args)

    def getPixel(self, *args):
        return _MosaifyPy_Linux.Image_getPixel(self, *args)

    def setPixels(self, *args):
        return _MosaifyPy_Linux.Image_setPixels(self, *args)

    def getNumberOfComponents(self):
        return _MosaifyPy_Linux.Image_getNumberOfComponents(self)

    def getWidth(self):
        return _MosaifyPy_Linux.Image_getWidth(self)

    def getHeight(self):
        return _MosaifyPy_Linux.Image_getHeight(self)

    def getFilename(self):
        return _MosaifyPy_Linux.Image_getFilename(self)

    def getBytesPerPixel(self):
        return _MosaifyPy_Linux.Image_getBytesPerPixel(self)

    def getDataPtr(self):
        return _MosaifyPy_Linux.Image_getDataPtr(self)

    def getDataSize(self):
        return _MosaifyPy_Linux.Image_getDataSize(self)

    def generate(self, *args):
        return _MosaifyPy_Linux.Image_generate(self, *args)

    def drawLine(self, *args):
        return _MosaifyPy_Linux.Image_drawLine(self, *args)

    def blur(self):
        return _MosaifyPy_Linux.Image_blur(self)

    def setAlpha(self, *args):
        return _MosaifyPy_Linux.Image_setAlpha(self, *args)

    def hasAlpha(self):
        return _MosaifyPy_Linux.Image_hasAlpha(self)

    def preMultiplyAlpha(self):
        return _MosaifyPy_Linux.Image_preMultiplyAlpha(self)

    def flip(self):
        return _MosaifyPy_Linux.Image_flip(self)

    def rotate(self):
        return _MosaifyPy_Linux.Image_rotate(self)

    def resize(self, *args):
        return _MosaifyPy_Linux.Image_resize(self, *args)

    def clip(self, *args):
        return _MosaifyPy_Linux.Image_clip(self, *args)

    def isWidthHeightPowerOf2(self):
        return _MosaifyPy_Linux.Image_isWidthHeightPowerOf2(self)

    def copyData(self, dataPtr, width, height, components, filename):
        return _MosaifyPy_Linux.Image_copyData(self, dataPtr, width, height, components, filename)

    def setId(self, _id):
        return _MosaifyPy_Linux.Image_setId(self, _id)

    def getId(self):
        return _MosaifyPy_Linux.Image_getId(self)

# Register Image in _MosaifyPy_Linux:
_MosaifyPy_Linux.Image_swigregister(Image)


def getMosaicPath(mosaify):
    return _MosaifyPy_Linux.getMosaicPath(mosaify)

def getMosaicPreviewPath(mosaify):
    return _MosaifyPy_Linux.getMosaicPreviewPath(mosaify)

def getMosaicTilePreviewPath(mosaify, _id):
    return _MosaifyPy_Linux.getMosaicTilePreviewPath(mosaify, _id)


